theme: jekyll-theme-architect

footer-links:
  email: vinitshahdeo@gmail.com
  facebook: vinit.shahdeo
  github: vinitshahdeo
  instagram: vinitshahdeo
  linkedin: vinitshahdeo
  pinterest:
  twitter: Vinit_Shahdeo
  googleplus: vinitshahdeo
